select e.*
,am.TREATMENT
,am.OFFER
from   PROCESSED.BE_CAMPAIGN.V_MARKETING_AUDIENCE_ALL_CAMPAIGNS am
    join PROCESSED.BE_CAMPAIGN.SALES_CAMPAIGN c
    on c.CAMPAIGN_YEAR_MONTH = am.CAMPAIGN
     join PROCESSED.BE_CAMPAIGN.V_BE_ORDERS_SIMPLE e
on am.CAMPAIGN = e.CAMPAIGN_YEAR_MONTH
and am.UID = e.UID
and DESCRIPTION ilike '%window%'
where c.LIST_BUILD_START_DATE>= dateadd(year,-1,current_date)
and CAMPAIGN_NAME_FOR_EMAIL <>'Ascent'